FROM node:12 as build-stage
WORKDIR /
COPY /template .
RUN yarn cache clean
RUN yarn install
RUN yarn build

FROM nginx as production-stage
RUN mkdir -p /app/
COPY --from=build-stage //build /app/
COPY /template/nginx.conf /etc/nginx/nginx.conf