[build]
publish = "public"
command = "CI=false yarn build"
targetPort = 3000

#####################################################################
### REDIRECTS
#####################################################################
## https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

########################################################
### General redirects
#[[redirects]]
#from = "/privacy"
#to = "/legal/privacy"
