name: Databricks Update & Databricks Install Pypi Test


on:
 pull_request:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8 #install the python version needed

    - name: execute py
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        python -m pip install --upgrade databricks-cli
        databricks repos update --path /Repos/research/prod --branch main
    - name: Trigger notebook from PR branch
      uses: databricks/run-notebook@v0
      with:
        local-notebook-path: bancor_research/bancor_simulator/tests/notebooks/pypi-installer-test.py
        existing-cluster-id: 0718-131334-gdlfepzf

