# This is a basic workflow to run regression tests

name: CI-regression-tests


on: [pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8 #install the python version needed
    - run: python setup.py install
    - run: python -i regression/test.py 1
    - run: python -i regression/test.py 2

